[Piotr Tag]
Lukaszpietrzykowski/patient-service-api pull request #24
Opened 2022-03-25 09:16 UTC by piotrtag1

[SOP-8]
[Dodanie interfejsu DepartmentRepository]

2022-03-25 16:01 UTC, Lukaszpietrzykowski requested changes

2022-03-25 16:01 UTC, Lukaszpietrzykowski commented on src/main/java/com/sop/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<PatientEntity,Long> {
tu powinno byc DepartmentEntity

2022-03-25 16:53 UTC, piotrtag1 commented on src/main/java/com/sop/repository/DepartmentRepository.java
> +public interface DepartmentRepository extends JpaRepository<PatientEntity,Long> {
Oba, już poprawiam

2022-03-27 14:59 UTC, piotrtag1 commented
Poprawione

2022-03-27 17:34 UTC, Lukaszpietrzykowski approved these changes

2022-03-27 17:34 UTC, merged